# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'angel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(981, 558)
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.picture = QtWidgets.QLabel(Dialog)
        self.picture.setGeometry(QtCore.QRect(590, 100, 400, 430))
        self.picture.setStyleSheet("")
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap(":/newPrefix/output-onlinejpgtools.png"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        self.title1 = QtWidgets.QLabel(Dialog)
        self.title1.setGeometry(QtCore.QRect(60, 20, 811, 121))
        self.title1.setStyleSheet("image: url(:/newPrefix/maintitle (2).png);")
        self.title1.setObjectName("title1")
        self.voiceanimated = QtWidgets.QLabel(Dialog)
        self.voiceanimated.setGeometry(QtCore.QRect(30, 300, 561, 131))
        self.voiceanimated.setStyleSheet("")
        self.voiceanimated.setText("")
        self.voiceanimated.setPixmap(QtGui.QPixmap(":/newPrefix/voiceanimatedgif.gif"))
        self.voiceanimated.setScaledContents(True)
        self.voiceanimated.setObjectName("voiceanimated")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 510, 101, 41))
        self.commandLinkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"text-decoration: underline;\n"
"font: 75 14pt \"Times New Roman\";\n"
"color: rgb(13, 239, 249);")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.picture.raise_()
        self.voiceanimated.raise_()
        self.title1.raise_()
        self.commandLinkButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title1.setText(_translate("Dialog", "TextLabel"))
        self.commandLinkButton.setText(_translate("Dialog", "STOP"))
import testing_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
