# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashscreen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(920, 600)
        SplashScreen.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg = QtWidgets.QLabel(self.centralwidget)
        self.Bg.setGeometry(QtCore.QRect(0, 0, 920, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Bg.setFont(font)
        self.Bg.setStyleSheet("background-image: url(:/newPrefix/blue gradient.png);")
        self.Bg.setText("")
        self.Bg.setObjectName("Bg")
        self.microphoneicon = QtWidgets.QLabel(self.centralwidget)
        self.microphoneicon.setGeometry(QtCore.QRect(-110, 260, 300, 400))
        self.microphoneicon.setStyleSheet("image: url(:/newPrefix/MP trans.png);")
        self.microphoneicon.setText("")
        self.microphoneicon.setScaledContents(True)
        self.microphoneicon.setObjectName("microphoneicon")
        self.title_ai = QtWidgets.QLabel(self.centralwidget)
        self.title_ai.setGeometry(QtCore.QRect(50, 40, 820, 65))
        self.title_ai.setStyleSheet("image: url(:/newPrefix/title1(2).png);")
        self.title_ai.setText("")
        self.title_ai.setObjectName("title_ai")
        self.subtitle = QtWidgets.QLabel(self.centralwidget)
        self.subtitle.setGeometry(QtCore.QRect(600, 200, 251, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.subtitle.setFont(font)
        self.subtitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.subtitle.setObjectName("subtitle")
        self.subicon = QtWidgets.QLabel(self.centralwidget)
        self.subicon.setGeometry(QtCore.QRect(90, 200, 80, 80))
        self.subicon.setStyleSheet("")
        self.subicon.setText("")
        self.subicon.setPixmap(QtGui.QPixmap(":/newPrefix/newsicon.png"))
        self.subicon.setScaledContents(True)
        self.subicon.setObjectName("subicon")
        self.subicon_3 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_3.setGeometry(QtCore.QRect(195, 400, 75, 75))
        self.subicon_3.setText("")
        self.subicon_3.setPixmap(QtGui.QPixmap(":/newPrefix/messageicon.png"))
        self.subicon_3.setScaledContents(True)
        self.subicon_3.setObjectName("subicon_3")
        self.subicon_4 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_4.setGeometry(QtCore.QRect(160, 250, 70, 70))
        self.subicon_4.setText("")
        self.subicon_4.setPixmap(QtGui.QPixmap(":/newPrefix/searchicon.png"))
        self.subicon_4.setScaledContents(True)
        self.subicon_4.setObjectName("subicon_4")
        self.subicon_5 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_5.setGeometry(QtCore.QRect(145, 355, 50, 50))
        self.subicon_5.setText("")
        self.subicon_5.setPixmap(QtGui.QPixmap(":/newPrefix/tempicon.png"))
        self.subicon_5.setScaledContents(True)
        self.subicon_5.setObjectName("subicon_5")
        self.subicon_7 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_7.setGeometry(QtCore.QRect(110, 305, 55, 55))
        self.subicon_7.setText("")
        self.subicon_7.setPixmap(QtGui.QPixmap(":/newPrefix/settingicon.png"))
        self.subicon_7.setScaledContents(True)
        self.subicon_7.setObjectName("subicon_7")
        self.subicon_6 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_6.setGeometry(QtCore.QRect(200, 315, 80, 80))
        self.subicon_6.setText("")
        self.subicon_6.setPixmap(QtGui.QPixmap(":/newPrefix/codingicon.png"))
        self.subicon_6.setScaledContents(True)
        self.subicon_6.setObjectName("subicon_6")
        self.subicon_8 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_8.setGeometry(QtCore.QRect(150, 465, 60, 60))
        self.subicon_8.setText("")
        self.subicon_8.setPixmap(QtGui.QPixmap(":/newPrefix/dateicon.png"))
        self.subicon_8.setScaledContents(True)
        self.subicon_8.setObjectName("subicon_8")
        self.subicon_9 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_9.setGeometry(QtCore.QRect(170, 525, 70, 70))
        self.subicon_9.setText("")
        self.subicon_9.setPixmap(QtGui.QPixmap(":/newPrefix/systemicon.png"))
        self.subicon_9.setScaledContents(True)
        self.subicon_9.setObjectName("subicon_9")
        self.subicon_10 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_10.setGeometry(QtCore.QRect(142, 415, 45, 45))
        self.subicon_10.setText("")
        self.subicon_10.setPixmap(QtGui.QPixmap(":/newPrefix/camicon.png"))
        self.subicon_10.setScaledContents(True)
        self.subicon_10.setObjectName("subicon_10")
        self.subicon_2 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_2.setGeometry(QtCore.QRect(120, 520, 50, 50))
        self.subicon_2.setText("")
        self.subicon_2.setPixmap(QtGui.QPixmap(":/newPrefix/shutdownicon.png"))
        self.subicon_2.setScaledContents(True)
        self.subicon_2.setObjectName("subicon_2")
        self.subicon_14 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_14.setGeometry(QtCore.QRect(220, 477, 60, 60))
        self.subicon_14.setText("")
        self.subicon_14.setPixmap(QtGui.QPixmap(":/newPrefix/timeicon.png"))
        self.subicon_14.setScaledContents(True)
        self.subicon_14.setObjectName("subicon_14")
        self.subicon_13 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_13.setGeometry(QtCore.QRect(10, 250, 50, 50))
        self.subicon_13.setText("")
        self.subicon_13.setPixmap(QtGui.QPixmap(":/newPrefix/locationicon.png"))
        self.subicon_13.setScaledContents(True)
        self.subicon_13.setObjectName("subicon_13")
        self.subicon_12 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_12.setGeometry(QtCore.QRect(30, 190, 60, 60))
        self.subicon_12.setText("")
        self.subicon_12.setPixmap(QtGui.QPixmap(":/newPrefix/mailicon.png"))
        self.subicon_12.setScaledContents(True)
        self.subicon_12.setObjectName("subicon_12")
        self.subicon_11 = QtWidgets.QLabel(self.centralwidget)
        self.subicon_11.setGeometry(QtCore.QRect(70, 275, 45, 45))
        self.subicon_11.setText("")
        self.subicon_11.setPixmap(QtGui.QPixmap(":/newPrefix/interneticon.png"))
        self.subicon_11.setScaledContents(True)
        self.subicon_11.setObjectName("subicon_11")
        self.title_va = QtWidgets.QLabel(self.centralwidget)
        self.title_va.setGeometry(QtCore.QRect(50, 120, 820, 65))
        self.title_va.setStyleSheet("image: url(:/newPrefix/title1(1).png);")
        self.title_va.setText("")
        self.title_va.setObjectName("title_va")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(430, 300, 180, 60))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(172, 175, 178);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(106, 106, 106, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    font: 60 12pt \"Times New Roman\";\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:hover\n"
"{font: 75 16pt \"Times New Roman\";\n"
"    background-color: rgb(199, 199, 199);\n"
"}\n"
"QPushButton:pressed \n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.start.setObjectName("start")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(320, 540, 450, 20))
        self.progressBar.setStyleSheet(" QProgressBar{\n"
"    background-color: rgb(0, 0, 0);\n"
"color: rgb(255,255,255);\n"
"border-style: none;\n"
"border-radius: 6px;\n"
"text-align : center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 6px;\n"
"    \n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(106, 106, 106, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.subtitle.setText(_translate("SplashScreen", "-I\'m your assistant ANGELINA"))
        self.start.setText(_translate("SplashScreen", "Start"))
import splashscreen_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
